package it.unito.di.sarlexceptions.test.exceptions

import io.sarl.core.Failure

event MyException extends Failure {
	
	var e : Exception

}
